### ISSUE TITLE
modem_manager: add audio support

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode-allwinner#2]
Route audio from microphone to modem and from modem to earpiece. This will enable basic voice call support.

**Comment by nfeske** [comment]
Wow, that looks excellent! Thank you very much for implementing this crucial feature in such a palatable form. :-) The run script with the essential AT commands is perfect for getting started.

Some minor feedback on the code:

* Couldn't the content of the `_init` method be moved into the constructor?

* To avoid global state as much as possible, it would be nice to avoid the various `access_t` instances. I think in most cases, we could get away be addressing bits directly instead of fiddling with the `access_t` value. For example, the following code
  ```
  Earpiece_control1::Enable_pa::set(_earpiece1, 1);
  Earpiece_control1::Mute_off::set(_earpiece1,  1);
  Earpiece_control1::Volume::set(_earpiece1, 0x1f); /* maximum volume */
  write<Earpiece_control1>(_earpiece1);
  ```
  could likely be written as
  ```
  write<Earpiece_control1::Enable_pa>(1);
  write<Earpiece_control1::Mute_off>(1);
  write<Earpiece_control1::Volume>(0x1f);  /* maximum volume */
  ```

  Granted, the latter style results in more read/write operations under the hood. But it makes the code a bit simpler. So in cases like this - if multiple bits don't need to be flipped atomically and performance is no concern - we should use the latter style.

**Comment by ssumpf** [comment]
@nfeske: 0445162 changes the style for the analog part as suggested.

**Comment by ssumpf** [comment]
@nfeske: f872127 sets the microphone to non-can mode.

**Comment by nfeske** [comment]
Thanks a lot. This looks fantastic!

**Comment by nfeske** [comment]
Merged to staging.

**Comment by ssumpf** [comment]
@nfeske: b22b9ca compiles with strict warnings.

**Comment by nfeske** [comment]
Merge to master.
