### ISSUE TITLE
sculpt: update morph browser presets

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode-allwinner#25]
Update the morph browser presets for Sculpt 23.10.

**Comment by cproc** [comment]
Commit 1efd5ef updates the presets. On my first tests, the browser appeared to be slower than on Sculpt 23.04 for some reason. For example, during the "YT: Audio Video Sync Test" it often took seconds for the video animation to update.

**Comment by nfeske** [comment]
Have you applied the base-hw performance tweak of commit https://github.com/nfeske/genode/commit/ee230ec91ad4d5bde2697ceb55dcdef696c1ec2e on your branch?

**Comment by cproc** [comment]
> Have you applied the base-hw performance tweak of commit [nfeske/genode@ee230ec](https://github.com/nfeske/genode/commit/ee230ec91ad4d5bde2697ceb55dcdef696c1ec2e) on your branch?

That was missing and solved the problem.

**Comment by nfeske** [comment]
@skalk, would it make sense to make the tweaked value the default?

**Comment by skalk** [comment]
The tweaked value means that the minimum PD session RAM quota necessary for the page-cache of every component (base-hw) gets increased from 512K+ to 4M+. Given that already without the tweak the used PD session RAM quota is significantly higher under base-hw than other kernels this difference will get even bigger. On the other hand, we've seen page-cache shortage so far only regarding monster-applications like the web-browser.
So, obviously a more flexible implementation of the page-cache resp. page-allocator would be cool to meet the requirements for memory-intensive applications and others. Short-term solution could be to make the increased value the default. It might interfer with some RAM quotas of our automated tests.

**Comment by nfeske** [comment]
It's strange that I don't have to adjust any RAM quota when applying the patch. The entirety of Sculpt runs just fine. If the effect on the RAM was as dramatic as you said, I think I would have noticed. I asked because the commit induces no such trouble but has a very positive effect on the browser performance.

> only regarding monster-applications like the web-browser

For the PinePhone, this application is part of the base-line feature set. When thinking of the system images officially released by Genode Labs, the browser performance is immediately visible to each user. So it should better be fast(er) by default.

**Comment by chelmuth** [comment]
Merged in sculpt-23.10.
