### ISSUE TITLE
USB: enable EHCI controller support on the A64 SoC

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode-allwinner#3]
This is a prerequisite to the PinePhone mobile data connectivity and related to https://github.com/genodelabs/genode/issues/4557.

**Comment by ssumpf** [comment]
@nfeske: Labels 'Feature' and 'Fixed'.

**Comment by nfeske** [comment]
I have some minor remarks regarding commit 86be4a63b7ad4aa10c2bcc19b3a72171a67925e0.

* It would be nice to add a file header to each new file to stay consistent with the other drivers.
* The commented-out lines in the Linux config should better remain at a topic branch. Should a commented out option be actually frequently used, it's probably fine to leave it here. But in this case, it should be accompanied by a comment describing how it is useful.
* Any whitespace at the end of a file should be removed.
* Given the line https://github.com/ssumpf/genode-allwinner/commit/86be4a63b7ad4aa10c2bcc19b3a72171a67925e0#diff-c2af4549d62f92f13c211803c240f53ca820a73082b5bcc34763b0b9ab1ec4afR733, I wonder if you may have manually edited the `generated_dummies.c` file? We should really abstain from manually curating this file so that anyone can easily update it using our tools. Just to go sure, could you try re-generating the file?
* As a minor style nitpick, the following code snippet looks quite noisy.
  ```
  unsigned long start = Lx_kit::env().timer.curr_time().trunc_to_plain_us().value;
  while (Lx_kit::env().timer.curr_time().trunc_to_plain_us().value < (start + usec)) { ; }
  ```
  I think it could benefit from using a local lamba function as follows (just drafted)
  ```
  auto curr_usec = [&]
  {
    return Lx_kit::env().timer.curr_time().trunc_to_plain_us().value;
  };

  unsigned long const start = curr_usec();

  while (curr_usec() < start + usec) { }
  ```
  Granted, these are more lines, but they become more easy to follow.

**Comment by ssumpf** [comment]
@nfeske: 024023e addresses you comments

**Comment by nfeske** [comment]
Thanks a lot! I merged the result as commit aa825bcb77740f4c2c9413c1033eac4c3a4df58c to staging.

**Comment by ssumpf** [comment]
@nfeske: c417cde adds documentation for the modem's data configuration.

**Comment by nfeske** [comment]
@ssumpf Superb! I merged your commit right away.
